# .travis.yml
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails42.gemfile
#matrix:
#  exclude:
#    - rbenv: 2.0.0
#      gemfile: gemfiles/rails2.gemfile
script: "bundle exec rake spec"
